<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4151f93f-8326-4890-80b7-a0b49c750384</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ComicReviewer.Domain\ComicReviewer.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Domain\" />
  </ItemGroup>

</Project>
